services:
  _defaults:
    autowire: true
    autoconfigure: true

  App\Api\Response\ResponseFactory:
    class: App\Api\Response\ResponseFactory

  App\Api\Controller\ApiController:
    class: App\Api\Controller\ApiController
    tags: ['controller.service_arguments']
    arguments:
      $projectionRepository: '@.App\Infrastructure\ReadModel\ProjectionDbRepository'
