imports:
    - { resource: services/currency_pairs_parsers.yaml }
    - { resource: services/currency_pair.yaml }
    - { resource: services/read_model.yaml }

services:
    _defaults:
        autowire: true
        autoconfigure: true

    #App\:
        #resource: '../src/'
        #exclude:
            #- '../src/functions.php'
            #- '../src/Kernel.php'
            #- '../src/App/Infrastructure/CurrencyPairsParser/CBRGuzzleParser'

    .App\Console\ParseCBRQuotesCommand:
        class: App\Console\ParseCBRQuotesCommand
        arguments:
            $parser: '@.App\Infrastructure\CurrencyPairsParser\CBRGuzzleParser'

    .serializer.property_normalizer:
        class: Symfony\Component\Serializer\Normalizer\PropertyNormalizer
        tags: [serializer.normalizer]
